artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: 'https://www.ceasacampinas.com.br/sites/ceasacampinas.com.br/files/cotacoes/{year}/{month}/{day}%2004%202024.pdf'
  source_url_params:
    year: 2024
    month: 04
    day: 19
  local_data_file: artifacts/data_ingestion/ceasa_campinas_202404.zip
  unzip_dir: artifacts/data_ingestion